# Invalid label: If there are changes in /projects AND other top-level directories.
Invalid:
  - all:
      - changed-files:
        - 'projects/**'
        - '!projects/**'
        
# Submission label: Apply when there are changes ONLY within /projects.
Submission:
  - all:
      - changed-files:
        - 'projects/**'
      - any:
          - changed-files:
            - '!*/**'

# Dev label: Apply when there are changes ONLY outside /projects.
Dev:
  - all:
      - changed-files:
        - '*'
      - any:
          - changed-files:
            - '!projects/**'
